# Permalinks
permalink:           pretty

# Setup
title:               BBC Recipes Archive
tagline:             'The BBC Recipes Archive… archived'
description:         'The BBC Recipes Archive… archived'
url:                 https://bbcrecipes.github.io
baseurl:             'https://bbcrecipes.github.io'
paginate:            5
paginate_path: "/blog/page:num/"

# About/contact
author:
  name:              David Darnes
  url:               https://twitter.com/daviddarnes
  email:             me@daviddarnes.com

# Custom vars
version:             1.0.0

# Recipes collection
collections:
  recipes:
    output: true
    permalink: /recipes/:path/
