# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               BBC Recipes Archive
tagline:             'The BBC Recipes Archive… archived'
description:         'The BBC Recipes Archive… archived'
url:                 https://bbcrecipes.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              David Darnes
  url:               https://twitter.com/daviddarnes
  email:             me@daviddarnes.com

# Custom vars
version:             1.0.0

# Recipes collection
collections:
  recipes:
    output: true
    permalink: /recipes/:path/
